
# This file is automatically generated, you probably don't want to edit this

processROptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "processROptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            varY = NULL,
            varX = NULL,
            varMed = NULL,
            varCov = NULL,
            varModW = NULL,
            varModZ = NULL,
            modNum = "mod1",
            cnfInt = "cnf_95",
            botSmp = "bot_5k",
            botSav = FALSE,
            botCoe = FALSE,
            shwCvM = FALSE,
            visInt = FALSE,
            shwTEM = FALSE,
            pwCnId = FALSE,
            effSze = FALSE,
            stdCff = FALSE,
            intXxM = FALSE,
            cntMnP = "cntNon",
            hetCns = "hetNon",
            decDig = "decDg4",
            prbInt = "prbP10",
            cndVal = "cndPrc",
            outJnN = FALSE,
            mctVrX = "mctNnX",
            mctVrW = "mctNnW",
            mctVrZ = "mctNnZ", ...) {

            super$initialize(
                package='processR',
                name='processR',
                requiresData=TRUE,
                ...)

            private$..varY <- jmvcore::OptionVariable$new(
                "varY",
                varY)
            private$..varX <- jmvcore::OptionVariable$new(
                "varX",
                varX)
            private$..varMed <- jmvcore::OptionVariables$new(
                "varMed",
                varMed)
            private$..varCov <- jmvcore::OptionVariables$new(
                "varCov",
                varCov)
            private$..varModW <- jmvcore::OptionVariable$new(
                "varModW",
                varModW)
            private$..varModZ <- jmvcore::OptionVariable$new(
                "varModZ",
                varModZ)
            private$..modNum <- jmvcore::OptionList$new(
                "modNum",
                modNum,
                options=list(
                    "mod0",
                    "mod1",
                    "mod2",
                    "mod3",
                    "mod4",
                    "mod4_2",
                    "mod4_3",
                    "mod5",
                    "mod6",
                    "mod6_3",
                    "mod6_4",
                    "mod7",
                    "mod8",
                    "mod9",
                    "mod10",
                    "mod11",
                    "mod12",
                    "mod13",
                    "mod14",
                    "mod15",
                    "mod16",
                    "mod17",
                    "mod18",
                    "mod19",
                    "mod20",
                    "mod21",
                    "mod22",
                    "mod23",
                    "mod24",
                    "mod25",
                    "mod26",
                    "mod27",
                    "mod28",
                    "mod29",
                    "mod30",
                    "mod31",
                    "mod35",
                    "mod36",
                    "mod40",
                    "mod41",
                    "mod45",
                    "mod49",
                    "mod50",
                    "mod58",
                    "mod58_2",
                    "mod59",
                    "mod60",
                    "mod61",
                    "mod62",
                    "mod63",
                    "mod64",
                    "mod65",
                    "mod66",
                    "mod67",
                    "mod74",
                    "mod75",
                    "mod76"),
                default="mod1")
            private$..cnfInt <- jmvcore::OptionList$new(
                "cnfInt",
                cnfInt,
                options=list(
                    "cnf_90",
                    "cnf_95",
                    "cnf_99"),
                default="cnf_95")
            private$..botSmp <- jmvcore::OptionList$new(
                "botSmp",
                botSmp,
                options=list(
                    "bot__0",
                    "bot_1k",
                    "bot_2k",
                    "bot_5k",
                    "bot10k",
                    "bot20k",
                    "bot50k"),
                default="bot_5k")
            private$..botSav <- jmvcore::OptionBool$new(
                "botSav",
                botSav,
                default=FALSE)
            private$..botCoe <- jmvcore::OptionBool$new(
                "botCoe",
                botCoe,
                default=FALSE)
            private$..shwCvM <- jmvcore::OptionBool$new(
                "shwCvM",
                shwCvM,
                default=FALSE)
            private$..visInt <- jmvcore::OptionBool$new(
                "visInt",
                visInt,
                default=FALSE)
            private$..shwTEM <- jmvcore::OptionBool$new(
                "shwTEM",
                shwTEM,
                default=FALSE)
            private$..pwCnId <- jmvcore::OptionBool$new(
                "pwCnId",
                pwCnId,
                default=FALSE)
            private$..effSze <- jmvcore::OptionBool$new(
                "effSze",
                effSze,
                default=FALSE)
            private$..stdCff <- jmvcore::OptionBool$new(
                "stdCff",
                stdCff,
                default=FALSE)
            private$..intXxM <- jmvcore::OptionBool$new(
                "intXxM",
                intXxM,
                default=FALSE)
            private$..cntMnP <- jmvcore::OptionList$new(
                "cntMnP",
                cntMnP,
                options=list(
                    "cntNon",
                    "cntAll",
                    "cntCnt"),
                default="cntNon")
            private$..hetCns <- jmvcore::OptionList$new(
                "hetCns",
                hetCns,
                options=list(
                    "hetNon",
                    "hetHC0",
                    "hetHC1",
                    "hetHC2",
                    "hetHC3",
                    "hetHC4"),
                default="hetNon")
            private$..decDig <- jmvcore::OptionList$new(
                "decDig",
                decDig,
                options=list(
                    "decDg2",
                    "decDg3",
                    "decDg4",
                    "decDg5",
                    "decDg6",
                    "decDg7",
                    "decDg8"),
                default="decDg4")
            private$..prbInt <- jmvcore::OptionList$new(
                "prbInt",
                prbInt,
                options=list(
                    "prbAlw",
                    "prbP20",
                    "prbP10",
                    "prbP05",
                    "prbP01"),
                default="prbP10")
            private$..cndVal <- jmvcore::OptionList$new(
                "cndVal",
                cndVal,
                options=list(
                    "cndPrc",
                    "cndSDv"),
                default="cndPrc")
            private$..outJnN <- jmvcore::OptionBool$new(
                "outJnN",
                outJnN,
                default=FALSE)
            private$..mctVrX <- jmvcore::OptionList$new(
                "mctVrX",
                mctVrX,
                options=list(
                    "mctNnX",
                    "mctInX",
                    "mctSqX",
                    "mctHlX",
                    "mctEfX"),
                default="mctNnX")
            private$..mctVrW <- jmvcore::OptionList$new(
                "mctVrW",
                mctVrW,
                options=list(
                    "mctNnW",
                    "mctInW",
                    "mctSqW",
                    "mctHlW",
                    "mctEfW"),
                default="mctNnW")
            private$..mctVrZ <- jmvcore::OptionList$new(
                "mctVrZ",
                mctVrZ,
                options=list(
                    "mctNnZ",
                    "mctInZ",
                    "mctSqZ",
                    "mctHlZ",
                    "mctEfZ"),
                default="mctNnZ")

            self$.addOption(private$..varY)
            self$.addOption(private$..varX)
            self$.addOption(private$..varMed)
            self$.addOption(private$..varCov)
            self$.addOption(private$..varModW)
            self$.addOption(private$..varModZ)
            self$.addOption(private$..modNum)
            self$.addOption(private$..cnfInt)
            self$.addOption(private$..botSmp)
            self$.addOption(private$..botSav)
            self$.addOption(private$..botCoe)
            self$.addOption(private$..shwCvM)
            self$.addOption(private$..visInt)
            self$.addOption(private$..shwTEM)
            self$.addOption(private$..pwCnId)
            self$.addOption(private$..effSze)
            self$.addOption(private$..stdCff)
            self$.addOption(private$..intXxM)
            self$.addOption(private$..cntMnP)
            self$.addOption(private$..hetCns)
            self$.addOption(private$..decDig)
            self$.addOption(private$..prbInt)
            self$.addOption(private$..cndVal)
            self$.addOption(private$..outJnN)
            self$.addOption(private$..mctVrX)
            self$.addOption(private$..mctVrW)
            self$.addOption(private$..mctVrZ)
        }),
    active = list(
        varY = function() private$..varY$value,
        varX = function() private$..varX$value,
        varMed = function() private$..varMed$value,
        varCov = function() private$..varCov$value,
        varModW = function() private$..varModW$value,
        varModZ = function() private$..varModZ$value,
        modNum = function() private$..modNum$value,
        cnfInt = function() private$..cnfInt$value,
        botSmp = function() private$..botSmp$value,
        botSav = function() private$..botSav$value,
        botCoe = function() private$..botCoe$value,
        shwCvM = function() private$..shwCvM$value,
        visInt = function() private$..visInt$value,
        shwTEM = function() private$..shwTEM$value,
        pwCnId = function() private$..pwCnId$value,
        effSze = function() private$..effSze$value,
        stdCff = function() private$..stdCff$value,
        intXxM = function() private$..intXxM$value,
        cntMnP = function() private$..cntMnP$value,
        hetCns = function() private$..hetCns$value,
        decDig = function() private$..decDig$value,
        prbInt = function() private$..prbInt$value,
        cndVal = function() private$..cndVal$value,
        outJnN = function() private$..outJnN$value,
        mctVrX = function() private$..mctVrX$value,
        mctVrW = function() private$..mctVrW$value,
        mctVrZ = function() private$..mctVrZ$value),
    private = list(
        ..varY = NA,
        ..varX = NA,
        ..varMed = NA,
        ..varCov = NA,
        ..varModW = NA,
        ..varModZ = NA,
        ..modNum = NA,
        ..cnfInt = NA,
        ..botSmp = NA,
        ..botSav = NA,
        ..botCoe = NA,
        ..shwCvM = NA,
        ..visInt = NA,
        ..shwTEM = NA,
        ..pwCnId = NA,
        ..effSze = NA,
        ..stdCff = NA,
        ..intXxM = NA,
        ..cntMnP = NA,
        ..hetCns = NA,
        ..decDig = NA,
        ..prbInt = NA,
        ..cndVal = NA,
        ..outJnN = NA,
        ..mctVrX = NA,
        ..mctVrW = NA,
        ..mctVrZ = NA)
)

processRResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="processR")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="processR"))}))

processRBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "processRBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'processR',
                name = 'processR',
                version = c(1,0,0),
                options = options,
                results = processRResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' processR
#'
#' 
#' @param data .
#' @param varY .
#' @param varX .
#' @param varMed .
#' @param varCov .
#' @param varModW .
#' @param varModZ .
#' @param modNum .
#' @param cnfInt .
#' @param botSmp .
#' @param botSav .
#' @param botCoe .
#' @param shwCvM .
#' @param visInt .
#' @param shwTEM .
#' @param pwCnId .
#' @param effSze .
#' @param stdCff .
#' @param intXxM .
#' @param cntMnP .
#' @param hetCns .
#' @param decDig .
#' @param prbInt .
#' @param cndVal .
#' @param outJnN .
#' @param mctVrX .
#' @param mctVrW .
#' @param mctVrZ .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
processR <- function(
    data,
    varY,
    varX,
    varMed,
    varCov,
    varModW,
    varModZ,
    modNum = "mod1",
    cnfInt = "cnf_95",
    botSmp = "bot_5k",
    botSav = FALSE,
    botCoe = FALSE,
    shwCvM = FALSE,
    visInt = FALSE,
    shwTEM = FALSE,
    pwCnId = FALSE,
    effSze = FALSE,
    stdCff = FALSE,
    intXxM = FALSE,
    cntMnP = "cntNon",
    hetCns = "hetNon",
    decDig = "decDg4",
    prbInt = "prbP10",
    cndVal = "cndPrc",
    outJnN = FALSE,
    mctVrX = "mctNnX",
    mctVrW = "mctNnW",
    mctVrZ = "mctNnZ") {

    if ( ! requireNamespace('jmvcore'))
        stop('processR requires jmvcore to be installed (restart may be required)')

    if ( ! missing(varY)) varY <- jmvcore::resolveQuo(jmvcore::enquo(varY))
    if ( ! missing(varX)) varX <- jmvcore::resolveQuo(jmvcore::enquo(varX))
    if ( ! missing(varMed)) varMed <- jmvcore::resolveQuo(jmvcore::enquo(varMed))
    if ( ! missing(varCov)) varCov <- jmvcore::resolveQuo(jmvcore::enquo(varCov))
    if ( ! missing(varModW)) varModW <- jmvcore::resolveQuo(jmvcore::enquo(varModW))
    if ( ! missing(varModZ)) varModZ <- jmvcore::resolveQuo(jmvcore::enquo(varModZ))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varY), varY, NULL),
            `if`( ! missing(varX), varX, NULL),
            `if`( ! missing(varMed), varMed, NULL),
            `if`( ! missing(varCov), varCov, NULL),
            `if`( ! missing(varModW), varModW, NULL),
            `if`( ! missing(varModZ), varModZ, NULL))


    options <- processROptions$new(
        varY = varY,
        varX = varX,
        varMed = varMed,
        varCov = varCov,
        varModW = varModW,
        varModZ = varModZ,
        modNum = modNum,
        cnfInt = cnfInt,
        botSmp = botSmp,
        botSav = botSav,
        botCoe = botCoe,
        shwCvM = shwCvM,
        visInt = visInt,
        shwTEM = shwTEM,
        pwCnId = pwCnId,
        effSze = effSze,
        stdCff = stdCff,
        intXxM = intXxM,
        cntMnP = cntMnP,
        hetCns = hetCns,
        decDig = decDig,
        prbInt = prbInt,
        cndVal = cndVal,
        outJnN = outJnN,
        mctVrX = mctVrX,
        mctVrW = mctVrW,
        mctVrZ = mctVrZ)

    analysis <- processRClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
